<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>FriendsFX</AssemblyName>
    <Title>FriendsFX</Title>
    <Authors>Lateblight</Authors>
    <Company>Lateblight</Company>
    <Product>FriendsFX</Product>
    <Description>Automatically manages battle effect visibilities for friends anywhere in the world.</Description>
    <Punchline>Full battle effects for friends, limited effects otherwise!</Punchline>
    <Version>1.1.1.0</Version>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

</Project>